services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_LOG_LEVEL=debug
      - N8N_CUSTOM_EXTENSIONS=/data/custom
    volumes:
      - ./dist:/data/custom
      - ~/.n8n:/home/node/.n8n
    restart: unless-stopped